from django.conf.urls import patterns, url

urlpatterns = patterns('transit.views',
                       url(r'^tb/incoming$', 'tb_incoming', name='tb_incoming'),
                       url(r'^tb/outgoing', 'tb_outgoing', name='tb_outgoing'),
                       url(r'^tb/create$', 'show_tb_form', name='create_tb'),
                       url(r'^tb/get_awbs$', 'ajax_get_tb_awbs', name='ajax_get_tb_awbs'),
                       url(r'^tb/in_scanning$', 'ajax_in_scanning_awb', name='ajax_in_scanning_awb'),
                       url(r'^tb/create_tb$', 'ajax_create_tb', name='ajax_create_tb'),
                       url(r'^mts/incoming$', 'mts_incoming', name='mts_incoming'),
                       url(r'^mts/outgoing', 'mts_outgoing', name='mts_outgoing'),
                       url(r'^mts/get_tbs$', 'ajax_get_tbs', name='ajax_get_tbs'),
                       url(r'^mts/create$', 'show_mts_form', name='create_mts'),
                       url(r'^mts/create_mts$', 'ajax_create_mts', name='ajax_create_mts'),
                       url(r'^mts/update_status', 'mts_update_status', name='mts_update_status'),
                       url(r'^drs$', 'drs', name='drs'),
                       url(r'^drs/create$', 'drs_in_scanning', name='drs_in_scanning'),
                       url(r'^drs/get_awbs$', 'ajax_get_drs_awbs', name='ajax_get_drs_awbs'),
                       url(r'^drs/create_drs$', 'ajax_create_drs', name='ajax_create_drs'),
                       url(r'^drs/update_status$', 'drs_update_status', name='drs_update_status'),
                       url(r'^drs/awb_status_update$', 'drs_awb_update_status', name='drs_awb_update_status'),
                       url(r'^drs/get_print_sheet', 'drs_get_print_sheet', name='drs_get_print_sheet'),
                       url(r'^dto/get_print_sheet', 'dto_get_print_sheet', name='dto_get_print_sheet'),
                       url(r'^drs/awb_cancel_scan$', 'drs_awb_cancel_scan', name='drs_awb_cancel_scan'),
                       url(r'^drs/(\d+)$', 'drs_detail', name='drs_detail'),
                       url(r'^tb/(\d+)$', 'tb_detail', name='tb_detail'),
                       url(r'^mts/tb/(\d+)$', 'tb_detail', name='mts_tb_detail'),
                       url(r'^mts/(\d+)$', 'mts_detail', name='mts_detail'),
                       url(r'^dto$', 'dto', name='drs'),
                       url(r'^dto/create$', 'dto_in_scanning', name='dto_in_scanning'),
                       url(r'^dto/get_awbs$', 'ajax_get_dto_awbs', name='ajax_get_dto_awbs'),
                       url(r'^dto/create_dto$', 'ajax_create_dto', name='ajax_create_dto'),
                       url(r'^dto/(\d+)$', 'dto_detail', name='dto_detail'),
                       url(r'^drs/drs_awb_status_update$', 'drs_awb_status_update', name='drs_awb_status_update'),
                       url(r'^dto/awb_status_update', 'dto_awb_update_status', name='drs_awb_update_status'),
                       #url(r'^dto/get_print_sheet', 'drs_get_print_sheet', name='drs_get_print_sheet'),
                       url(r'^get_count$', 'get_count', name='get_count'),
)
